### ISSUE TITLE
Ongoing development?

### ISSUE THREAD

**Issue by RichardJECooke** [HarryStevens/geometric#30]
Hi, I'm trying to find a good geometry library to use on top of p5.js for drawing.

I see this library doesn't do anything with curves, paths, or vectors. Or altering polygons, like clipping, union, etc.

Do you plan to add more features at any time? Or do you know of a more advanced geometry library please? This is the only one I can find :(

**Comment by HarryStevens** [comment]
When you say "altering polygons", what you seem to be referring to is boolean operations. I think boolean operations are probably beyond the scope of Geometric.js because boolean operations often return multiple polygons, which can be represented with GeoJSON but not with native JavaScript arrays like those use in Geometric.js. For boolean operations with GeoJSON, I recommend [martinez](https://github.com/w8r/martinez).

Curves are also beyond the scope of Geometric.js because all the primitives in Geometric.js use arrays of points. Of course, you can approximate a curve with a list of points (I made a little library called [swoopy](https://github.com/HarryStevens/swoopy) that does a bit of this). I'm not sure what you mean by paths, but if you're referring to SVG paths, that is beyond the scope of this library. As for vectors, you should probably use a linear algebra library.
